feat: add readonly to component property types
ErikssonJoakim/React-project pull request #3
Opened 2022-04-19 16:12 UTC by ErikssonJoakim

2022-04-20 09:19 UTC, fredericvilcot approved these changes
Good! 👍
Maybe you should check your formatting rules to add consistency (quotes, semi-colon, ...)

2022-04-22 09:12 UTC, fredericvilcot requested changes

2022-04-22 09:12 UTC, fredericvilcot commented on .gitignore
> +.prettierrc
You should not ignore the `prettier` configuration file because it's a shared configuration between all the contributors that ensures the same formatting rules for everyone.

2022-04-28 11:55 UTC, ErikssonJoakim commented on .gitignore
> +.prettierrc
Outdated

2022-04-28 11:57 UTC, ErikssonJoakim commented
> Good! 👍 Maybe you should check your formatting rules to add consistency (quotes, semi-colon, ...)

Adressed in branch #4

2022-04-28 12:19 UTC, fredericvilcot requested changes
Please, reformat first this files with `prettier` to ensure consistency

2022-05-09 12:01 UTC, closed without merging